apiVersion: v1
kind: Service
metadata:
  name: {{ include "holiday-peak-service.fullname" . }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  selector:
    app: {{ .Values.serviceName }}
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP
